from .xyb_exception import XYBException

class AccountError(XYBException): pre='USER'